include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: false
    always_specify_types: false
    avoid_annotating_with_dynamic: true
    avoid_catches_without_on_clauses: false
    avoid_double_and_int_checks: false
    avoid_empty_else: true
    avoid_escaping_inner_quotes: true
    avoid_print: false
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: false
    prefer_single_quotes: true
    public_member_api_docs: false
    sized_box_for_whitespace: true
    type_annotate_public_apis: false
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: false
    avoid_function_literals_in_foreach_calls: false
    lowercase_with_underscores: false

